[package]
name = "KC-Overlay"
version = "0.6.0"
edition = "2021"
authors = ["jafkc2"]
repository = "https://github.com/jafkc2/KC-Overlay"

[profile.release]
strip = true
lto = true

[dependencies]
iced = {version = "0.14.0-dev", features = ["tokio", "image"]}
reqwest = {version = "0.12.12", features = ["json"]}
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
open = "5.3.2"
rfd = "0.15.2"
chrono = "0.4"
screen_size = "0.1.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[patch.crates-io]
iced = { git = "https://github.com/iced-rs/iced", rev = "97f1db3783dca5a4f60a9f89668613de4dfe9edd" }
iced_core = { git = "https://github.com/iced-rs/iced", rev = "97f1db3783dca5a4f60a9f89668613de4dfe9edd" }
